<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta property="og:title" content="Chapter 4 Richness Measures | Poverty and Inequality with Complex Survey Data" />
<meta property="og:type" content="book" />

<meta property="og:description" content="A book about the R convey package" />
<meta name="github-repo" content="guilhermejacob/context" />

<meta name="author" content="Guilherme Jacob, Anthony Damico, and Djalma Pessoa" />

<meta name="date" content="2023-08-15" />

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta name="description" content="A book about the R convey package">

<title>Chapter 4 Richness Measures | Poverty and Inequality with Complex Survey Data</title>

<link href="libs/tufte-css-2015.12.29/tufte-fonts.css" rel="stylesheet" />
<link href="libs/tufte-css-2015.12.29/tufte-background.css" rel="stylesheet" />
<link href="libs/tufte-css-2015.12.29/tufte-italics.css" rel="stylesheet" />
<link href="libs/tufte-css-2015.12.29/tufte.css" rel="stylesheet" />


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="toc.css" type="text/css" />

</head>

<body>



<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul>
<li class="has-sub"><a href="index.html#introduction" id="toc-introduction"><span class="toc-section-number">1</span> Introduction</a>
<ul>
<li><a href="1.1-install.html#install" id="toc-install"><span class="toc-section-number">1.1</span> Installation</a></li>
<li><a href="1.2-survey.html#survey" id="toc-survey"><span class="toc-section-number">1.2</span> Complex surveys and statistical inference</a></li>
<li><a href="1.3-usage-examples.html#usage-examples" id="toc-usage-examples"><span class="toc-section-number">1.3</span> Usage Examples</a></li>
<li><a href="1.4-lin.html#lin" id="toc-lin"><span class="toc-section-number">1.4</span> Underlying Calculations</a></li>
<li><a href="1.5-var.html#var" id="toc-var"><span class="toc-section-number">1.5</span> The Variance Estimator</a></li>
<li><a href="1.6-influence-functions.html#influence-functions" id="toc-influence-functions"><span class="toc-section-number">1.6</span> Influence Functions</a></li>
<li><a href="1.7-influence-function-examples.html#influence-function-examples" id="toc-influence-function-examples"><span class="toc-section-number">1.7</span> Influence Function Examples</a></li>
<li><a href="1.8-examples-of-linearization-using-the-influence-function.html#examples-of-linearization-using-the-influence-function" id="toc-examples-of-linearization-using-the-influence-function"><span class="toc-section-number">1.8</span> Examples of Linearization Using the Influence Function</a></li>
<li><a href="1.9-replication-designs.html#replication-designs" id="toc-replication-designs"><span class="toc-section-number">1.9</span> Replication Designs</a></li>
<li><a href="1.10-decomposition.html#decomposition" id="toc-decomposition"><span class="toc-section-number">1.10</span> Decomposition</a></li>
</ul></li>
<li class="has-sub"><a href="2-poverty.html#poverty" id="toc-poverty"><span class="toc-section-number">2</span> Poverty Indices</a>
<ul>
<li><a href="2.1-at-risk-of-poverty-threshold-svyarpt.html#at-risk-of-poverty-threshold-svyarpt" id="toc-at-risk-of-poverty-threshold-svyarpt"><span class="toc-section-number">2.1</span> At Risk of Poverty Threshold (svyarpt)</a></li>
<li><a href="2.2-at-risk-of-poverty-ratio-svyarpr.html#at-risk-of-poverty-ratio-svyarpr" id="toc-at-risk-of-poverty-ratio-svyarpr"><span class="toc-section-number">2.2</span> At Risk of Poverty Ratio (svyarpr)</a></li>
<li><a href="2.3-relative-median-income-ratio-svyrmir.html#relative-median-income-ratio-svyrmir" id="toc-relative-median-income-ratio-svyrmir"><span class="toc-section-number">2.3</span> Relative Median Income Ratio (svyrmir)</a></li>
<li><a href="2.4-relative-median-poverty-gap-svyrmpg.html#relative-median-poverty-gap-svyrmpg" id="toc-relative-median-poverty-gap-svyrmpg"><span class="toc-section-number">2.4</span> Relative Median Poverty Gap (svyrmpg)</a></li>
<li><a href="2.5-median-income-below-the-at-risk-of-poverty-threshold-svypoormed.html#median-income-below-the-at-risk-of-poverty-threshold-svypoormed" id="toc-median-income-below-the-at-risk-of-poverty-threshold-svypoormed"><span class="toc-section-number">2.5</span> Median Income Below the At Risk of Poverty Threshold (svypoormed)</a></li>
<li><a href="2.6-foster-greer-thorbecke-class-svyfgt-svyfgtdec.html#foster-greer-thorbecke-class-svyfgt-svyfgtdec" id="toc-foster-greer-thorbecke-class-svyfgt-svyfgtdec"><span class="toc-section-number">2.6</span> Foster-Greer-Thorbecke class (svyfgt, svyfgtdec)</a></li>
<li><a href="2.7-watts-poverty-measure-svywatts-svywattsdec.html#watts-poverty-measure-svywatts-svywattsdec" id="toc-watts-poverty-measure-svywatts-svywattsdec"><span class="toc-section-number">2.7</span> Watts poverty measure (svywatts, svywattsdec)</a></li>
</ul></li>
<li class="has-sub"><a href="3-inequality.html#inequality" id="toc-inequality"><span class="toc-section-number">3</span> Inequality Measurement</a>
<ul>
<li><a href="3.1-the-gender-pay-gap-svygpg.html#the-gender-pay-gap-svygpg" id="toc-the-gender-pay-gap-svygpg"><span class="toc-section-number">3.1</span> The Gender Pay Gap (svygpg)</a></li>
<li><a href="3.2-quintile-share-ratio-svyqsr.html#quintile-share-ratio-svyqsr" id="toc-quintile-share-ratio-svyqsr"><span class="toc-section-number">3.2</span> Quintile Share Ratio (svyqsr)</a></li>
<li><a href="3.3-lorenz-curve-svylorenz.html#lorenz-curve-svylorenz" id="toc-lorenz-curve-svylorenz"><span class="toc-section-number">3.3</span> Lorenz Curve (svylorenz)</a></li>
<li><a href="3.4-gini-index-svygini.html#gini-index-svygini" id="toc-gini-index-svygini"><span class="toc-section-number">3.4</span> Gini index (svygini)</a></li>
<li><a href="3.5-zenga-index-svyzenga.html#zenga-index-svyzenga" id="toc-zenga-index-svyzenga"><span class="toc-section-number">3.5</span> Zenga index (svyzenga)</a></li>
<li><a href="3.6-entropy-based-measures.html#entropy-based-measures" id="toc-entropy-based-measures"><span class="toc-section-number">3.6</span> Entropy-based Measures</a></li>
<li><a href="3.7-generalized-entropy-and-decomposition-svygei-svygeidec.html#generalized-entropy-and-decomposition-svygei-svygeidec" id="toc-generalized-entropy-and-decomposition-svygei-svygeidec"><span class="toc-section-number">3.7</span> Generalized Entropy and Decomposition (svygei, svygeidec)</a></li>
<li><a href="3.8-j-divergence-and-decomposition-svyjdiv-svyjdivdec.html#j-divergence-and-decomposition-svyjdiv-svyjdivdec" id="toc-j-divergence-and-decomposition-svyjdiv-svyjdivdec"><span class="toc-section-number">3.8</span> J-Divergence and Decomposition (svyjdiv, svyjdivdec)</a></li>
<li><a href="3.9-atkinson-index-svyatk.html#atkinson-index-svyatk" id="toc-atkinson-index-svyatk"><span class="toc-section-number">3.9</span> Atkinson index (svyatk)</a></li>
<li><a href="3.10-which-inequality-measure-should-be-used.html#which-inequality-measure-should-be-used" id="toc-which-inequality-measure-should-be-used"><span class="toc-section-number">3.10</span> Which inequality measure should be used?</a></li>
</ul></li>
<li><a href="4-richness-measures.html#richness-measures" id="toc-richness-measures"><span class="toc-section-number">4</span> Richness Measures</a></li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<div id="richness-measures" class="section level1" number="4">
<h1><span class="header-section-number">Chapter 4</span> Richness Measures</h1>
<p>Richness (or Affluence) measures provide another approach for understanding
income concentration. Unlike inequality measures, that are sensitive to the
changes over the entire income distribution, richness measures are restricted
to the top.</p>
<p>In that sense, they work like “inverted” poverty measures: while the poverty
focus axiom states that poverty measures should be insensitive to changes
in the incomes of the non-poor, the richness focus
axiom states that richness measures should remain unaltered by changes in the
incomes of the non-rich.</p>
<p>Also like poverty measures, richness measures also rely on a “richness threshold”:
those above that threshold are regarded as rich, while those below are regarded
as non-rich.<label for="tufte-sn-5" class="margin-toggle sidenote-number">5</label><input type="checkbox" id="tufte-sn-5" class="margin-toggle"><span class="sidenote"><span class="sidenote-number">5</span> Not necessarily, but including the poor</span>
Like for poverty measurement, these richness thresholds can be somewhat arbitrary;
<span class="citation">Medeiros (<label for="tufte-mn-91" class="margin-toggle">&#8853;</label><input type="checkbox" id="tufte-mn-91" class="margin-toggle">2006<span class="marginnote">Medeiros, Marcelo. 2006. <span>“<span class="nocase">The Rich and the Poor: The Construction of an Affluence Line from the Poverty Line</span>.”</span> <em>Social Indicators Research</em> 78 (1): 1–18. <a href="https://doi.org/10.1007/s11205-005-7156-1">https://doi.org/10.1007/s11205-005-7156-1</a>.</span>)</span> provide a nice review of proposed richness thresholds and also propose
one possible approach with practical and theoretical grounds.</p>
<p><span class="citation">Peichl, Schaefer, and Scheicher (<label for="tufte-mn-92" class="margin-toggle">&#8853;</label><input type="checkbox" id="tufte-mn-92" class="margin-toggle">2010<span class="marginnote">Peichl, Andreas, Thilo Schaefer, and Christoph Scheicher. 2010. <span>“<span class="nocase">Measuring Richness and Poverty: A micro data application to Europe and Germany</span>.”</span> <em>Review of Income and Wealth</em> 56 (3): 597–619. https://doi.org/<a href="https://doi.org/10.1111/j.1475-4991.2010.00404.x">https://doi.org/10.1111/j.1475-4991.2010.00404.x</a>.</span>)</span> presented an axiomatic study of richness measures. They classify
richness measures in two types depending on the effect of income transfers among
the rich.
A <em>concave</em> measure follows the concave transfer axiom (T1): the measure should
increase when a progressive transfer occurs among two rich individuals.
On the other hand, a <em>convex</em> measure follows the convex transfer axiom (T2):
the measure should <em>decrease</em> when a progressive transfer occurs among two rich
individuals.</p>
<p>The reasoning behind the concave transfer axiom is that such progressive transfer
would make the income distribution among the rich more internally homogeneous,
“clustering” their incomes and interests.
On the other hand, convex richness measures are more sensitive to the inequality
among the rich.
In a sense, concave measures are related to the income polarization approach,
while convex measures are related to the income inequality approach.</p>
<p><span class="citation">Peichl, Schaefer, and Scheicher (<label for="tufte-mn-93" class="margin-toggle">&#8853;</label><input type="checkbox" id="tufte-mn-93" class="margin-toggle">2010<span class="marginnote">Peichl, Andreas, Thilo Schaefer, and Christoph Scheicher. 2010. <span>“<span class="nocase">Measuring Richness and Poverty: A micro data application to Europe and Germany</span>.”</span> <em>Review of Income and Wealth</em> 56 (3): 597–619. https://doi.org/<a href="https://doi.org/10.1111/j.1475-4991.2010.00404.x">https://doi.org/10.1111/j.1475-4991.2010.00404.x</a>.</span>)</span> also presented a general class of richness measures, proposing three
particular sub-classes: the (concave) Chakravarty class, the concave-FGT class and the convex-FGT class, defined at the population level as:</p>
<p><span class="math display">\[
\begin{aligned}
R^{Cha}_\gamma &amp;= \frac{1}{N} \sum_{k \in U} \bigg[( 1 - \bigg( \frac{z_r}{y_k}\bigg)^\gamma \bigg] \delta( y_k \geq z_r ) , \quad \gamma &gt; 0 \\
R^{FGT,T1}_\gamma &amp;= \frac{1}{N} \sum_{k \in U} \bigg( \frac{y_k - z_r}{y_k} \bigg)^\gamma \delta( y_k \geq z_r ) , \quad \gamma \in [0,1) \\
R^{FGT,T2}_\gamma &amp;= \frac{1}{N} \sum_{k \in U} \bigg( \frac{y_k - z_r}{z_r} \bigg)^\gamma \delta( y_k \geq z_r ) , \quad \gamma &gt; 1 \\
\end{aligned}
\]</span>
where <span class="math inline">\(z_r\)</span> is the richness threshold and <span class="math inline">\(\gamma\)</span> is a sensitivity parameter.</p>
<p>To estimate these measures, <span class="citation">Brzezinski (<label for="tufte-mn-94" class="margin-toggle">&#8853;</label><input type="checkbox" id="tufte-mn-94" class="margin-toggle">2014<span class="marginnote">Brzezinski, Michal. 2014. <span>“Statistical Inference for Richness Measures.”</span> <em>Applied Economics</em> 46 (14): 1599–1608. <a href="https://doi.org/10.1080/00036846.2014.880106">https://doi.org/10.1080/00036846.2014.880106</a>.</span>)</span> proposed the estimators</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{R}^{Cha}_\gamma &amp;= \frac{1}{\widehat{N}} \sum_{k \in s} w_k \bigg[( 1 - \bigg( \frac{z_r}{y_k}\bigg)^\gamma \bigg] \delta( y_k \geq z_r ) , \quad \gamma &gt; 0 \\
\widehat{R}^{FGT,T1}_\gamma &amp;= \frac{1}{\widehat{N}} \sum_{k \in s} w_k \bigg( \frac{y_k - z_r}{y_k} \bigg)^\gamma \delta( y_k \geq z_r ) , \quad \gamma \in [0,1) \\
\widehat{R}^{FGT,T2}_\gamma &amp;= \frac{1}{\widehat{N}} \sum_{k \in s} w_k \bigg( \frac{y_k - z_r}{z_r} \bigg)^\gamma \delta( y_k \geq z_r ) , \quad \gamma &gt; 1 \\
\end{aligned}
\]</span>
where <span class="math inline">\(w_k\)</span> is the sampling (or calibration) weight.</p>
<p>In order to estimate the variance of these estimators, <span class="citation">Brzezinski (<label for="tufte-mn-95" class="margin-toggle">&#8853;</label><input type="checkbox" id="tufte-mn-95" class="margin-toggle">2014<span class="marginnote">Brzezinski, Michal. 2014. <span>“Statistical Inference for Richness Measures.”</span> <em>Applied Economics</em> 46 (14): 1599–1608. <a href="https://doi.org/10.1080/00036846.2014.880106">https://doi.org/10.1080/00036846.2014.880106</a>.</span>)</span> derived influence functions under the <span class="citation">Deville (<label for="tufte-mn-96" class="margin-toggle">&#8853;</label><input type="checkbox" id="tufte-mn-96" class="margin-toggle">1999<span class="marginnote">Deville, Jean-Claude. 1999. <span>“Variance Estimation for Complex Statistics and Estimators: Linearization and Residual Techniques.”</span> <em>Survey Methodology</em> 25 (2): 193–203. <a href="http://www.statcan.gc.ca/pub/12-001-x/1999002/article/4882-eng.pdf">http://www.statcan.gc.ca/pub/12-001-x/1999002/article/4882-eng.pdf</a>.</span>)</span> approach. These functions are the ones used in the <code>svyrich</code> function.</p>
<p><span class="citation">Brzezinski (<label for="tufte-mn-97" class="margin-toggle">&#8853;</label><input type="checkbox" id="tufte-mn-97" class="margin-toggle">2014<span class="marginnote">Brzezinski, Michal. 2014. <span>“Statistical Inference for Richness Measures.”</span> <em>Applied Economics</em> 46 (14): 1599–1608. <a href="https://doi.org/10.1080/00036846.2014.880106">https://doi.org/10.1080/00036846.2014.880106</a>.</span>)</span> also studied the reliability of the inference based on these estimators
using a model-based Monte Carlo simulation, which are also valid for (design-based)
simple random sampling with replacement. His results showed that inference for convex
measures are unreliable for convex measures — see vignette below for a design-based
approach with the same results.</p>
<hr />
<p><strong>A replication example</strong></p>
<p><span class="citation">Brzezinski (<label for="tufte-mn-98" class="margin-toggle">&#8853;</label><input type="checkbox" id="tufte-mn-98" class="margin-toggle">2014<span class="marginnote">Brzezinski, Michal. 2014. <span>“Statistical Inference for Richness Measures.”</span> <em>Applied Economics</em> 46 (14): 1599–1608. <a href="https://doi.org/10.1080/00036846.2014.880106">https://doi.org/10.1080/00036846.2014.880106</a>.</span>)</span> presented results using a model-based Monte Carlo — i.e., he simulated
several samples from the model and compared the behavior of the estimators with
the model-based parameters.
In the simulation below, we take a design-based approach: we take several samples
from a fixed finite population using a particular sampling design, compute the estimator
on each and compare them to the finite population parameter (not the model-based
parameter!).</p>
<p>For the sake of similarity, we start by simulating a large finite population (<span class="math inline">\(N = 10^5\)</span>)
using the same distribution from <span class="citation">Brzezinski (<label for="tufte-mn-99" class="margin-toggle">&#8853;</label><input type="checkbox" id="tufte-mn-99" class="margin-toggle">2014<span class="marginnote">Brzezinski, Michal. 2014. <span>“Statistical Inference for Richness Measures.”</span> <em>Applied Economics</em> 46 (14): 1599–1608. <a href="https://doi.org/10.1080/00036846.2014.880106">https://doi.org/10.1080/00036846.2014.880106</a>.</span>)</span>:</p>
<div class="sourceCode" id="cb438"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb438-1"><a href="4-richness-measures.html#cb438-1" tabindex="-1"></a><span class="co"># load libraries</span></span>
<span id="cb438-2"><a href="4-richness-measures.html#cb438-2" tabindex="-1"></a><span class="fu">library</span>(survey)</span>
<span id="cb438-3"><a href="4-richness-measures.html#cb438-3" tabindex="-1"></a><span class="fu">library</span>(convey)</span>
<span id="cb438-4"><a href="4-richness-measures.html#cb438-4" tabindex="-1"></a><span class="fu">library</span>(sampling)</span>
<span id="cb438-5"><a href="4-richness-measures.html#cb438-5" tabindex="-1"></a><span class="fu">library</span>(VGAM)</span>
<span id="cb438-6"><a href="4-richness-measures.html#cb438-6" tabindex="-1"></a></span>
<span id="cb438-7"><a href="4-richness-measures.html#cb438-7" tabindex="-1"></a><span class="co"># set random seed</span></span>
<span id="cb438-8"><a href="4-richness-measures.html#cb438-8" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2023</span>)</span>
<span id="cb438-9"><a href="4-richness-measures.html#cb438-9" tabindex="-1"></a></span>
<span id="cb438-10"><a href="4-richness-measures.html#cb438-10" tabindex="-1"></a><span class="co"># superpopulation parameters</span></span>
<span id="cb438-11"><a href="4-richness-measures.html#cb438-11" tabindex="-1"></a>scale.x0 <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb438-12"><a href="4-richness-measures.html#cb438-12" tabindex="-1"></a>shape.theta <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb438-13"><a href="4-richness-measures.html#cb438-13" tabindex="-1"></a>cha.beta <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb438-14"><a href="4-richness-measures.html#cb438-14" tabindex="-1"></a>fgt.alpha <span class="ot">&lt;-</span> <span class="fl">1.5</span></span>
<span id="cb438-15"><a href="4-richness-measures.html#cb438-15" tabindex="-1"></a>n.pop <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(<span class="dv">10</span> <span class="sc">^</span> <span class="dv">5</span>)</span>
<span id="cb438-16"><a href="4-richness-measures.html#cb438-16" tabindex="-1"></a></span>
<span id="cb438-17"><a href="4-richness-measures.html#cb438-17" tabindex="-1"></a><span class="co"># generate finite population</span></span>
<span id="cb438-18"><a href="4-richness-measures.html#cb438-18" tabindex="-1"></a>pop.df <span class="ot">&lt;-</span></span>
<span id="cb438-19"><a href="4-richness-measures.html#cb438-19" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">y1 =</span> <span class="fu">rparetoI</span>(n.pop  ,  scale.x0 , shape.theta))</span></code></pre></div>
<p>Then, we compute the finite population parameters using the simulated population:</p>
<div class="sourceCode" id="cb439"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb439-1"><a href="4-richness-measures.html#cb439-1" tabindex="-1"></a><span class="co"># richness measures: finite population parameters</span></span>
<span id="cb439-2"><a href="4-richness-measures.html#cb439-2" tabindex="-1"></a>cha.scores <span class="ot">&lt;-</span></span>
<span id="cb439-3"><a href="4-richness-measures.html#cb439-3" tabindex="-1"></a>  <span class="cf">function</span>(y , b , rho)</span>
<span id="cb439-4"><a href="4-richness-measures.html#cb439-4" tabindex="-1"></a>    <span class="fu">ifelse</span>(y <span class="sc">&gt;</span> rho , (<span class="dv">1</span> <span class="sc">-</span> (rho <span class="sc">/</span> y) <span class="sc">^</span> b) , <span class="dv">0</span>)</span>
<span id="cb439-5"><a href="4-richness-measures.html#cb439-5" tabindex="-1"></a>fgtt2.scores <span class="ot">&lt;-</span></span>
<span id="cb439-6"><a href="4-richness-measures.html#cb439-6" tabindex="-1"></a>  <span class="cf">function</span>(y , g , rho)</span>
<span id="cb439-7"><a href="4-richness-measures.html#cb439-7" tabindex="-1"></a>    <span class="fu">ifelse</span>(y <span class="sc">&gt;</span> rho , (y <span class="sc">/</span> rho <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">^</span> a , <span class="dv">0</span>)</span>
<span id="cb439-8"><a href="4-richness-measures.html#cb439-8" tabindex="-1"></a>median.fp <span class="ot">&lt;-</span> <span class="fu">quantile</span>(pop.df<span class="sc">$</span>y1 , .<span class="dv">50</span>)</span>
<span id="cb439-9"><a href="4-richness-measures.html#cb439-9" tabindex="-1"></a>rho.fp <span class="ot">&lt;-</span> <span class="dv">3</span> <span class="sc">*</span> median.fp</span>
<span id="cb439-10"><a href="4-richness-measures.html#cb439-10" tabindex="-1"></a>rHC.fp <span class="ot">&lt;-</span> <span class="fu">mean</span>(pop.df<span class="sc">$</span>y1 <span class="sc">&gt;</span> rho.fp)</span>
<span id="cb439-11"><a href="4-richness-measures.html#cb439-11" tabindex="-1"></a>rCha.fp <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">cha.scores</span>(pop.df<span class="sc">$</span>y1  , cha.beta , rho.fp))</span>
<span id="cb439-12"><a href="4-richness-measures.html#cb439-12" tabindex="-1"></a>rFGTT2.fp <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">cha.scores</span>(pop.df<span class="sc">$</span>y1  , fgt.alpha , rho.fp))</span></code></pre></div>
<p>For our sampling design, we select <span class="math inline">\(n = 1000\)</span> units using multinomial sampling,
with the variable <code>x.aux</code> as the size variable for the inclusion probabilities:</p>
<div class="sourceCode" id="cb440"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb440-1"><a href="4-richness-measures.html#cb440-1" tabindex="-1"></a><span class="co"># define sample size</span></span>
<span id="cb440-2"><a href="4-richness-measures.html#cb440-2" tabindex="-1"></a>n.sample <span class="ot">&lt;-</span> 1000L</span>
<span id="cb440-3"><a href="4-richness-measures.html#cb440-3" tabindex="-1"></a></span>
<span id="cb440-4"><a href="4-richness-measures.html#cb440-4" tabindex="-1"></a><span class="co"># inclusion probability</span></span>
<span id="cb440-5"><a href="4-richness-measures.html#cb440-5" tabindex="-1"></a>pop.df<span class="sc">$</span>x.aux <span class="ot">&lt;-</span> <span class="fu">plogis</span>( pop.df<span class="sc">$</span>y1 ) <span class="sc">/</span> <span class="fl">1.1</span></span>
<span id="cb440-6"><a href="4-richness-measures.html#cb440-6" tabindex="-1"></a>pop.df<span class="sc">$</span>pi1 <span class="ot">&lt;-</span> sampling<span class="sc">::</span><span class="fu">inclusionprobabilities</span>( pop.df<span class="sc">$</span>x.aux , n.sample )</span></code></pre></div>
<p>We run the procedure N and store the estimate objects using the code below:</p>
<div class="sourceCode" id="cb441"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb441-1"><a href="4-richness-measures.html#cb441-1" tabindex="-1"></a><span class="co"># define the number of simulation runs</span></span>
<span id="cb441-2"><a href="4-richness-measures.html#cb441-2" tabindex="-1"></a>mc.reps <span class="ot">&lt;-</span> 5000L</span>
<span id="cb441-3"><a href="4-richness-measures.html#cb441-3" tabindex="-1"></a></span>
<span id="cb441-4"><a href="4-richness-measures.html#cb441-4" tabindex="-1"></a><span class="co"># simulation runs</span></span>
<span id="cb441-5"><a href="4-richness-measures.html#cb441-5" tabindex="-1"></a>rep.list <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="fu">seq_len</span>(mc.reps) , <span class="cf">function</span>(this.iter) {</span>
<span id="cb441-6"><a href="4-richness-measures.html#cb441-6" tabindex="-1"></a>  <span class="co"># multinomial sampling</span></span>
<span id="cb441-7"><a href="4-richness-measures.html#cb441-7" tabindex="-1"></a>  this.sample <span class="ot">&lt;-</span> sampling<span class="sc">::</span><span class="fu">UPmultinomial</span>(pop.df<span class="sc">$</span>pi1)</span>
<span id="cb441-8"><a href="4-richness-measures.html#cb441-8" tabindex="-1"></a>  this.sample <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span>n.pop , this.sample)</span>
<span id="cb441-9"><a href="4-richness-measures.html#cb441-9" tabindex="-1"></a>  sample.df <span class="ot">&lt;-</span> pop.df[this.sample ,]</span>
<span id="cb441-10"><a href="4-richness-measures.html#cb441-10" tabindex="-1"></a>  sample.df<span class="sc">$</span>weights <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">/</span> sample.df<span class="sc">$</span>pi1</span>
<span id="cb441-11"><a href="4-richness-measures.html#cb441-11" tabindex="-1"></a>  des.obj <span class="ot">&lt;-</span></span>
<span id="cb441-12"><a href="4-richness-measures.html#cb441-12" tabindex="-1"></a>    <span class="fu">svydesign</span>(</span>
<span id="cb441-13"><a href="4-richness-measures.html#cb441-13" tabindex="-1"></a>      <span class="at">ids =</span> <span class="sc">~</span> <span class="dv">1</span> ,</span>
<span id="cb441-14"><a href="4-richness-measures.html#cb441-14" tabindex="-1"></a>      <span class="at">weights =</span> <span class="sc">~</span> weights ,</span>
<span id="cb441-15"><a href="4-richness-measures.html#cb441-15" tabindex="-1"></a>      <span class="at">data =</span> sample.df ,</span>
<span id="cb441-16"><a href="4-richness-measures.html#cb441-16" tabindex="-1"></a>      <span class="at">nest =</span> <span class="cn">FALSE</span></span>
<span id="cb441-17"><a href="4-richness-measures.html#cb441-17" tabindex="-1"></a>    )</span>
<span id="cb441-18"><a href="4-richness-measures.html#cb441-18" tabindex="-1"></a>  </span>
<span id="cb441-19"><a href="4-richness-measures.html#cb441-19" tabindex="-1"></a>  <span class="co"># run estimation</span></span>
<span id="cb441-20"><a href="4-richness-measures.html#cb441-20" tabindex="-1"></a>  des.obj <span class="ot">&lt;-</span> <span class="fu">convey_prep</span>(des.obj)</span>
<span id="cb441-21"><a href="4-richness-measures.html#cb441-21" tabindex="-1"></a>  rCha.hat <span class="ot">&lt;-</span></span>
<span id="cb441-22"><a href="4-richness-measures.html#cb441-22" tabindex="-1"></a>    <span class="fu">svyrich</span>(</span>
<span id="cb441-23"><a href="4-richness-measures.html#cb441-23" tabindex="-1"></a>      <span class="sc">~</span> y1 ,</span>
<span id="cb441-24"><a href="4-richness-measures.html#cb441-24" tabindex="-1"></a>      des.obj ,</span>
<span id="cb441-25"><a href="4-richness-measures.html#cb441-25" tabindex="-1"></a>      <span class="at">type_measure =</span> <span class="st">&quot;Cha&quot;</span> ,</span>
<span id="cb441-26"><a href="4-richness-measures.html#cb441-26" tabindex="-1"></a>      <span class="at">g =</span> cha.beta ,</span>
<span id="cb441-27"><a href="4-richness-measures.html#cb441-27" tabindex="-1"></a>      <span class="at">type_thresh =</span> <span class="st">&quot;relq&quot;</span> ,</span>
<span id="cb441-28"><a href="4-richness-measures.html#cb441-28" tabindex="-1"></a>      <span class="at">percent =</span> <span class="dv">3</span></span>
<span id="cb441-29"><a href="4-richness-measures.html#cb441-29" tabindex="-1"></a>    )</span>
<span id="cb441-30"><a href="4-richness-measures.html#cb441-30" tabindex="-1"></a>  <span class="fu">suppressWarnings</span>(</span>
<span id="cb441-31"><a href="4-richness-measures.html#cb441-31" tabindex="-1"></a>    rHC.hat <span class="ot">&lt;-</span></span>
<span id="cb441-32"><a href="4-richness-measures.html#cb441-32" tabindex="-1"></a>      <span class="fu">svyrich</span>(</span>
<span id="cb441-33"><a href="4-richness-measures.html#cb441-33" tabindex="-1"></a>        <span class="sc">~</span> y1 ,</span>
<span id="cb441-34"><a href="4-richness-measures.html#cb441-34" tabindex="-1"></a>        des.obj ,</span>
<span id="cb441-35"><a href="4-richness-measures.html#cb441-35" tabindex="-1"></a>        <span class="at">type_measure =</span> <span class="st">&quot;FGTT1&quot;</span> ,</span>
<span id="cb441-36"><a href="4-richness-measures.html#cb441-36" tabindex="-1"></a>        <span class="at">g =</span> <span class="dv">0</span> ,</span>
<span id="cb441-37"><a href="4-richness-measures.html#cb441-37" tabindex="-1"></a>        <span class="at">type_thresh =</span> <span class="st">&quot;relq&quot;</span>  ,</span>
<span id="cb441-38"><a href="4-richness-measures.html#cb441-38" tabindex="-1"></a>        <span class="at">percent =</span> <span class="dv">3</span></span>
<span id="cb441-39"><a href="4-richness-measures.html#cb441-39" tabindex="-1"></a>      )</span>
<span id="cb441-40"><a href="4-richness-measures.html#cb441-40" tabindex="-1"></a>  )</span>
<span id="cb441-41"><a href="4-richness-measures.html#cb441-41" tabindex="-1"></a>  <span class="fu">suppressWarnings</span>(</span>
<span id="cb441-42"><a href="4-richness-measures.html#cb441-42" tabindex="-1"></a>    rFGTT2.hat <span class="ot">&lt;-</span></span>
<span id="cb441-43"><a href="4-richness-measures.html#cb441-43" tabindex="-1"></a>      <span class="fu">svyrich</span>(</span>
<span id="cb441-44"><a href="4-richness-measures.html#cb441-44" tabindex="-1"></a>        <span class="sc">~</span> y1 ,</span>
<span id="cb441-45"><a href="4-richness-measures.html#cb441-45" tabindex="-1"></a>        des.obj ,</span>
<span id="cb441-46"><a href="4-richness-measures.html#cb441-46" tabindex="-1"></a>        <span class="at">type_measure =</span> <span class="st">&quot;FGTT2&quot;</span> ,</span>
<span id="cb441-47"><a href="4-richness-measures.html#cb441-47" tabindex="-1"></a>        <span class="at">g =</span> fgt.alpha ,</span>
<span id="cb441-48"><a href="4-richness-measures.html#cb441-48" tabindex="-1"></a>        <span class="at">type_thresh =</span> <span class="st">&quot;relq&quot;</span>  ,</span>
<span id="cb441-49"><a href="4-richness-measures.html#cb441-49" tabindex="-1"></a>        <span class="at">percent =</span> <span class="dv">3</span></span>
<span id="cb441-50"><a href="4-richness-measures.html#cb441-50" tabindex="-1"></a>      )</span>
<span id="cb441-51"><a href="4-richness-measures.html#cb441-51" tabindex="-1"></a>  )</span>
<span id="cb441-52"><a href="4-richness-measures.html#cb441-52" tabindex="-1"></a>  est.list <span class="ot">&lt;-</span> <span class="fu">list</span>(rHC.hat , rCha.hat , rFGTT2.hat)</span>
<span id="cb441-53"><a href="4-richness-measures.html#cb441-53" tabindex="-1"></a>  est.list</span>
<span id="cb441-54"><a href="4-richness-measures.html#cb441-54" tabindex="-1"></a>  </span>
<span id="cb441-55"><a href="4-richness-measures.html#cb441-55" tabindex="-1"></a>})</span></code></pre></div>
<p>To study the behavior of the estimators, we estimate their expected values, empirical
variance (for the main parameter) and mean squared error. To study the validity
of the normal approximation, we also estimate the percent coverage rate of the nominal
95% confidence interval. This is done using the function below:</p>
<div class="sourceCode" id="cb442"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb442-1"><a href="4-richness-measures.html#cb442-1" tabindex="-1"></a>sim.compile <span class="ot">&lt;-</span> <span class="cf">function</span>(ll ,</span>
<span id="cb442-2"><a href="4-richness-measures.html#cb442-2" tabindex="-1"></a>                        pv ,</span>
<span id="cb442-3"><a href="4-richness-measures.html#cb442-3" tabindex="-1"></a>                        <span class="at">level =</span> .<span class="dv">95</span> ,</span>
<span id="cb442-4"><a href="4-richness-measures.html#cb442-4" tabindex="-1"></a>                        <span class="at">na.rm =</span> <span class="cn">FALSE</span>) {</span>
<span id="cb442-5"><a href="4-richness-measures.html#cb442-5" tabindex="-1"></a>  <span class="co"># collect estimates</span></span>
<span id="cb442-6"><a href="4-richness-measures.html#cb442-6" tabindex="-1"></a>  mhat.vec <span class="ot">&lt;-</span> <span class="fu">sapply</span>(ll , coef)</span>
<span id="cb442-7"><a href="4-richness-measures.html#cb442-7" tabindex="-1"></a>  vhat.vec <span class="ot">&lt;-</span> <span class="fu">sapply</span>(ll , vcov)</span>
<span id="cb442-8"><a href="4-richness-measures.html#cb442-8" tabindex="-1"></a>  </span>
<span id="cb442-9"><a href="4-richness-measures.html#cb442-9" tabindex="-1"></a>  <span class="co"># estimate expected value</span></span>
<span id="cb442-10"><a href="4-richness-measures.html#cb442-10" tabindex="-1"></a>  mhat.exp <span class="ot">&lt;-</span> <span class="fu">mean</span>(mhat.vec , <span class="at">na.rm =</span> na.rm)</span>
<span id="cb442-11"><a href="4-richness-measures.html#cb442-11" tabindex="-1"></a>  vhat.exp <span class="ot">&lt;-</span> <span class="fu">mean</span>(vhat.vec , <span class="at">na.rm =</span> na.rm)</span>
<span id="cb442-12"><a href="4-richness-measures.html#cb442-12" tabindex="-1"></a>  </span>
<span id="cb442-13"><a href="4-richness-measures.html#cb442-13" tabindex="-1"></a>  <span class="co"># calculate empirical variance</span></span>
<span id="cb442-14"><a href="4-richness-measures.html#cb442-14" tabindex="-1"></a>  mhat.empvar <span class="ot">&lt;-</span> <span class="fu">var</span>(mhat.vec , <span class="at">na.rm =</span> na.rm)</span>
<span id="cb442-15"><a href="4-richness-measures.html#cb442-15" tabindex="-1"></a>  </span>
<span id="cb442-16"><a href="4-richness-measures.html#cb442-16" tabindex="-1"></a>  <span class="co"># estimate squared bias</span></span>
<span id="cb442-17"><a href="4-richness-measures.html#cb442-17" tabindex="-1"></a>  mhat.bias2 <span class="ot">&lt;-</span> (mhat.exp <span class="sc">-</span> pv) <span class="sc">^</span> <span class="dv">2</span></span>
<span id="cb442-18"><a href="4-richness-measures.html#cb442-18" tabindex="-1"></a>  vhat.bias2 <span class="ot">&lt;-</span> (vhat.exp <span class="sc">-</span> mhat.empvar) <span class="sc">^</span> <span class="dv">2</span></span>
<span id="cb442-19"><a href="4-richness-measures.html#cb442-19" tabindex="-1"></a>  </span>
<span id="cb442-20"><a href="4-richness-measures.html#cb442-20" tabindex="-1"></a>  <span class="co"># estimate mse</span></span>
<span id="cb442-21"><a href="4-richness-measures.html#cb442-21" tabindex="-1"></a>  mhat.mse <span class="ot">&lt;-</span> mhat.bias2 <span class="sc">+</span> mhat.empvar</span>
<span id="cb442-22"><a href="4-richness-measures.html#cb442-22" tabindex="-1"></a>  </span>
<span id="cb442-23"><a href="4-richness-measures.html#cb442-23" tabindex="-1"></a>  <span class="co"># estimate coverage rate</span></span>
<span id="cb442-24"><a href="4-richness-measures.html#cb442-24" tabindex="-1"></a>  ci.hats <span class="ot">&lt;-</span> <span class="fu">t</span>(<span class="fu">sapply</span>(ll , confint))</span>
<span id="cb442-25"><a href="4-richness-measures.html#cb442-25" tabindex="-1"></a>  ci.check <span class="ot">&lt;-</span></span>
<span id="cb442-26"><a href="4-richness-measures.html#cb442-26" tabindex="-1"></a>    <span class="fu">matrix</span>(<span class="fu">as.logical</span>(<span class="cn">NA</span>) , <span class="at">nrow =</span> <span class="fu">nrow</span>(ci.hats) , <span class="at">ncol =</span> <span class="dv">3</span>)</span>
<span id="cb442-27"><a href="4-richness-measures.html#cb442-27" tabindex="-1"></a>  ci.check[, <span class="dv">1</span>] <span class="ot">&lt;-</span> ci.hats[, <span class="dv">1</span>] <span class="sc">&lt;=</span> pv</span>
<span id="cb442-28"><a href="4-richness-measures.html#cb442-28" tabindex="-1"></a>  ci.check[, <span class="dv">2</span>] <span class="ot">&lt;-</span> ci.hats[, <span class="dv">2</span>] <span class="sc">&gt;=</span> pv</span>
<span id="cb442-29"><a href="4-richness-measures.html#cb442-29" tabindex="-1"></a>  ci.check[, <span class="dv">3</span>] <span class="ot">&lt;-</span> <span class="fu">apply</span>(ci.check[, <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>] , <span class="dv">1</span> , all)</span>
<span id="cb442-30"><a href="4-richness-measures.html#cb442-30" tabindex="-1"></a>  pcr.emp <span class="ot">&lt;-</span> <span class="fu">mean</span>(ci.check[, <span class="dv">3</span>] , <span class="at">na.rm =</span> na.rm)</span>
<span id="cb442-31"><a href="4-richness-measures.html#cb442-31" tabindex="-1"></a>  </span>
<span id="cb442-32"><a href="4-richness-measures.html#cb442-32" tabindex="-1"></a>  <span class="co"># setup final table</span></span>
<span id="cb442-33"><a href="4-richness-measures.html#cb442-33" tabindex="-1"></a>  <span class="fu">data.frame</span>(</span>
<span id="cb442-34"><a href="4-richness-measures.html#cb442-34" tabindex="-1"></a>    <span class="st">&quot;mc.reps&quot;</span> <span class="ot">=</span> <span class="fu">length</span>(ll) ,</span>
<span id="cb442-35"><a href="4-richness-measures.html#cb442-35" tabindex="-1"></a>    <span class="st">&quot;theta&quot;</span> <span class="ot">=</span> pv ,</span>
<span id="cb442-36"><a href="4-richness-measures.html#cb442-36" tabindex="-1"></a>    <span class="st">&quot;theta.hat&quot;</span> <span class="ot">=</span> mhat.exp ,</span>
<span id="cb442-37"><a href="4-richness-measures.html#cb442-37" tabindex="-1"></a>    <span class="st">&quot;theta.bias2&quot;</span> <span class="ot">=</span> mhat.bias2 ,</span>
<span id="cb442-38"><a href="4-richness-measures.html#cb442-38" tabindex="-1"></a>    <span class="st">&quot;theta.empvar&quot;</span> <span class="ot">=</span> mhat.empvar ,</span>
<span id="cb442-39"><a href="4-richness-measures.html#cb442-39" tabindex="-1"></a>    <span class="st">&quot;theta.hat.mse&quot;</span> <span class="ot">=</span> mhat.mse ,</span>
<span id="cb442-40"><a href="4-richness-measures.html#cb442-40" tabindex="-1"></a>    <span class="st">&quot;theta.varhat&quot;</span> <span class="ot">=</span> vhat.exp ,</span>
<span id="cb442-41"><a href="4-richness-measures.html#cb442-41" tabindex="-1"></a>    <span class="st">&quot;pcr&quot;</span> <span class="ot">=</span> pcr.emp</span>
<span id="cb442-42"><a href="4-richness-measures.html#cb442-42" tabindex="-1"></a>  )</span>
<span id="cb442-43"><a href="4-richness-measures.html#cb442-43" tabindex="-1"></a>}</span></code></pre></div>
<p>For the Headcount Richness Ratio (computed using the concave FGT measure), we have:</p>
<div class="sourceCode" id="cb443"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb443-1"><a href="4-richness-measures.html#cb443-1" tabindex="-1"></a>rhc.list <span class="ot">&lt;-</span> <span class="fu">lapply</span>(rep.list , <span class="st">`</span><span class="at">[[</span><span class="st">`</span> , <span class="dv">1</span>)</span>
<span id="cb443-2"><a href="4-richness-measures.html#cb443-2" tabindex="-1"></a><span class="fu">sim.compile</span>(rhc.list, rHC.fp)</span></code></pre></div>
<pre><code>##   mc.reps   theta  theta.hat  theta.bias2 theta.empvar theta.hat.mse
## 1    5000 0.05469 0.05452618 2.683797e-08 4.112616e-05    4.1153e-05
##   theta.varhat    pcr
## 1 4.336252e-05 0.9524</code></pre>
<p>Under this approach, the squared bias accounts for approx. 0.07% of the MSE, indicating
that the MSE of the estimator is reasonably approximated by its variance. Additionally,
the ratio between the expected value of the variance estimator and the empirical
variance is approx. 1.05, indicating that the variance estimates are expected to
be a (slighlty conservative, but) good approximation of the empirical variance.
Finally, the estimated percent coverage rate of 95.24% is close to the nominal
level of 95%, indicating that the confidence intervals are approximately valid.</p>
<p>For the Chakravarty measure, we have:</p>
<div class="sourceCode" id="cb445"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb445-1"><a href="4-richness-measures.html#cb445-1" tabindex="-1"></a>rcha.list <span class="ot">&lt;-</span> <span class="fu">lapply</span>(rep.list , <span class="st">`</span><span class="at">[[</span><span class="st">`</span> , <span class="dv">2</span>)</span>
<span id="cb445-2"><a href="4-richness-measures.html#cb445-2" tabindex="-1"></a><span class="fu">sim.compile</span>(rcha.list, rCha.fp)</span></code></pre></div>
<pre><code>##   mc.reps      theta  theta.hat  theta.bias2 theta.empvar theta.hat.mse
## 1    5000 0.02743915 0.02737177 4.538966e-09 1.428639e-05  1.429093e-05
##   theta.varhat    pcr
## 1 1.402416e-05 0.9428</code></pre>
<p>Under this approach, the squared bias is approx 0.03% of the MSE, indicating that
the MSE of the estimator is reasonably approximated by its variance. Additionally,
the ratio between the expected value of the variance estimator and the empirical
variance is approx. 0.98, indicating that the variance estimates are expected to
be a good approximation of the empirical variance. Finally, the estimated percent
coverage rate of 94.28% is close to the nominal level of 95%, indicating that the
confidence intervals are approximately valid.</p>
<p>For the convex FGT measure, we have:</p>
<div class="sourceCode" id="cb447"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb447-1"><a href="4-richness-measures.html#cb447-1" tabindex="-1"></a>rfgtt2.list <span class="ot">&lt;-</span> <span class="fu">lapply</span>(rep.list , <span class="st">`</span><span class="at">[[</span><span class="st">`</span> , <span class="dv">3</span>)</span>
<span id="cb447-2"><a href="4-richness-measures.html#cb447-2" tabindex="-1"></a><span class="fu">sim.compile</span>(rfgtt2.list, rFGTT2.fp)</span></code></pre></div>
<pre><code>##   mc.reps      theta theta.hat theta.bias2 theta.empvar theta.hat.mse
## 1    5000 0.02349189 0.1045973  0.00657808   0.01865219    0.02523027
##   theta.varhat    pcr
## 1   0.01857144 0.5212</code></pre>
<p>Under this approach, the squared bias is approx 26% of the MSE, indicating that
the <em>bias is substantial</em>. The ratio between the expected value of the variance
estimator and the empirical variance is approx. 1.00, indicating that the variance
estimates are expected to be a good approximation of the empirical variance (but
not of the MSE!). Finally, the estimated percent coverage rate of 52.12% is far
from the nominal level of 95%, indicating that the confidence intervals are invalid.
This comes from the fact that the estimator is very sensitive to the extreme values
and is the reason why <span class="citation">Brzezinski (<label for="tufte-mn-100" class="margin-toggle">&#8853;</label><input type="checkbox" id="tufte-mn-100" class="margin-toggle">2014<span class="marginnote">Brzezinski, Michal. 2014. <span>“Statistical Inference for Richness Measures.”</span> <em>Applied Economics</em> 46 (14): 1599–1608. <a href="https://doi.org/10.1080/00036846.2014.880106">https://doi.org/10.1080/00036846.2014.880106</a>.</span>)</span> does not recommend using convex richness measures.</p>

</div>
<p style="text-align: center;">
<a href="3.10-which-inequality-measure-should-be-used.html"><button class="btn btn-default">Previous</button></a>
</p>
</div>
</div>



</body>
</html>
